#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

export AARCHVM_ARGS="-smp 2 -smp-mode psci"
export AARCHVM_LINUX_DTB="dts/aarchvm-linux-smp.dtb"
export AARCHVM_TIMER_SCALE="${AARCHVM_TIMER_SCALE:-1}"
export AARCHVM_USERTEST_SNAPSHOT_STEPS="${AARCHVM_USERTEST_SNAPSHOT_STEPS:-12000000000}"
export AARCHVM_USERTEST_SNAPSHOT_TIMEOUT="${AARCHVM_USERTEST_SNAPSHOT_TIMEOUT:-900s}"
export AARCHVM_USERTEST_SNAPSHOT_VERIFY_STEPS="${AARCHVM_USERTEST_SNAPSHOT_VERIFY_STEPS:-50000000}"
export AARCHVM_USERTEST_SNAPSHOT_VERIFY_TIMEOUT="${AARCHVM_USERTEST_SNAPSHOT_VERIFY_TIMEOUT:-120s}"
export AARCHVM_USERTEST_SNAPSHOT_OUT="${AARCHVM_USERTEST_SNAPSHOT_OUT:-out/linux-smp-shell-v1.snap}"
export AARCHVM_USERTEST_SNAPSHOT_LOG="${AARCHVM_USERTEST_SNAPSHOT_LOG:-out/linux-smp-shell-v1-build.log}"
export AARCHVM_USERTEST_SNAPSHOT_VERIFY_LOG="${AARCHVM_USERTEST_SNAPSHOT_VERIFY_LOG:-out/linux-smp-shell-v1-verify.log}"

exec ./tests/linux/build_linux_shell_snapshot.sh
